import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Share_Tech_Mono } from 'next/font/google';
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/public-components/Header";
import Providers from "@/lib/tankstack/provider";
import { Footer } from "@/components/public-components/Footer";
import { auth } from "@/lib/auth/config";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const shareTechMono = Share_Tech_Mono({
  weight: '400', // Esta fonte geralmente só tem peso 400
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-share-tech', // Definimos um nome de variável CSS
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth.api.getSession({
    headers: await headers()
  })

  return (
    <html lang="pt" suppressHydrationWarning>
      <body className={`min-h-screen bg-background text-foreground antialiased ${shareTechMono.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <Providers>
            <Header session={session} />
            {children}
            <Footer />
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
